services:
  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - mired
    volumes:
      - ./data:/data
      - ./datalog:/datalog
    environment:
      ZOO_TICK_TIME: 2000

networks:
    mired:
        external: true