services:    
    pgadmin:
        image: dpage/pgadmin4:9.2
        ports: 
            - "8088:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
            - PGADMIN_LISTEN_PORT=80
        networks:
            - mired
networks:
    mired:
        external: true